# Numpy Crash Course

In [11]:
import numpy as np

In [12]:
np.__version__

'2.3.5'

In [13]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [14]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [16]:
arr = np.array(my_list) 

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(my_list)

list

# numpy arrange

In [20]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [21]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(3.0)  

array([0., 1., 2.])

In [23]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [27]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [28]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [29]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [30]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [31]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [32]:
np.arange(10,10) 

array([], dtype=int64)

In [33]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

In [ ]:
np.arange(0,10,3)

In [ ]:
np.arange(10,30,5,8)

# numpy zeros

In [ ]:
np.zeros(3) # parameter  tunning 

In [ ]:
np.zeros(5, dtype=int) # hyperparameter tunning 

In [ ]:
np.zeros((2,2), dtype=int)

In [ ]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

In [ ]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

In [ ]:
np.zeros((2,10))

In [ ]:
np.zeros((2,2))

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((10,30))

In [ ]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

In [ ]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

In [ ]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

In [ ]:
n

In [ ]:
n1

In [ ]:
print(np.zeros(n1))

# numpy with ones

In [ ]:
np.ones(3)

In [ ]:
np.ones(4, dtype=int) 

In [ ]:
np.ones(4)

In [ ]:
n

In [ ]:
np.ones(n)

In [ ]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

In [ ]:
np.

In [ ]:
np.twos((2,3)) 

In [34]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
np.ones(2)

In [ ]:
np.ones((2,4)) 

In [ ]:
np.ones((6,10),dtype = int) 

In [ ]:
np.twos((2,4))

In [ ]:
np.

In [ ]:
np.three((2,4))

In [ ]:
range(5)

In [35]:
r = range(5)
r

range(0, 5)

In [36]:
for i in r:
    print(i)

0
1
2
3
4


In [37]:
list(range(5))

[0, 1, 2, 3, 4]

In [38]:
range(1,10)

range(1, 10)

In [39]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
list(range(1,10,3))

[1, 4, 7]

In [41]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Random value

In [42]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
rand(3,2)
random.rand(3,2)

In [ ]:
np.random.rand(5)

In [43]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.randint(2,4)

In [ ]:
np.random.randint(2,20) # 2nd argument is exlusive 

In [ ]:
np.random.randint(0,1) 

In [ ]:
np.random.randint(10,20,5)

In [ ]:
np.random.randint(1,6,4)

In [44]:
np.random.rand(3)

array([0.04013938, 0.27925372, 0.42385362])

In [45]:
np.random.randint(1)  

0

In [46]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [ ]:
np.random.randint(-30,20,10) 

In [ ]:
np.random.randint(20,30,10) 

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [47]:
np.random.randint(10,21,3)

array([15, 13, 18], dtype=int32)

In [48]:
np.random.randint(1,12,10)

array([ 4,  5, 10, 11,  5,  4,  2,  5,  3,  8], dtype=int32)

In [49]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[22, 33, 16, 28, 29, 19, 15, 22, 11, 23],
       [39, 23, 32, 23, 21, 16, 30, 14, 31, 39],
       [20, 32, 33, 13, 34, 36, 33, 30, 18, 22],
       [10, 36, 25, 23, 18, 21, 39, 27, 34, 16],
       [12, 21, 39, 33, 34, 38, 35, 17, 32, 21],
       [26, 28, 17, 27, 26, 14, 38, 32, 36, 32],
       [21, 28, 18, 39, 10, 30, 39, 27, 39, 18],
       [34, 14, 12, 29, 26, 20, 29, 13, 29, 35],
       [29, 17, 15, 20, 27, 19, 18, 23, 18, 34],
       [23, 30, 28, 35, 11, 31, 31, 22, 37, 19]], dtype=int32)

In [50]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[21, 71, 12, 95, 37, 94, 82,  6,  6, 35, 74, 18],
       [ 7, 24, 88, 50, 29, 19,  8, 71, 93, 89, 94, 66],
       [ 6,  4, 70, 80, 94, 93, 10, 26, 16, 27, 22,  8],
       [23, 78, 38, 57, 26,  4, 17, 34, 67, 51,  9, 42],
       [61, 87,  3,  3, 44, 59, 98, 59, 62, 21, 81, 62],
       [56, 57, 92, 83, 32, 48, 25, 86, 53, 85, 87, 56],
       [77, 36, 72, 79, 20, 62, 70, 76, 64, 43,  1, 33],
       [95, 48, 86, 17, 10, 41, 30, 47, 90, 84, 73, 11],
       [17, 66, 25, 21, 49, 34,  4, 90, 92, 38,  7, 98],
       [52, 59, 93, 49, 62, 37, 60, 96, 51, 48, 87, 28],
       [82, 81, 82, 67, 18, 19, 27, 72, 89, 47, 87,  9],
       [44, 70, 99, 85, 25, 34, 13, 56, 68, 34, 44, 67]], dtype=int32)

In [51]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [53]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [54]:
type(b)

numpy.ndarray

In [55]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [56]:
b[:] 

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [57]:
b[1:3]

array([[11, 16, 18, 19],
       [14, 12, 12, 18]], dtype=int32)

In [58]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [59]:
b[1,2]

np.int32(18)

In [60]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [61]:
b[1,3]

np.int32(19)

In [62]:
b[1,-1]

np.int32(19)

In [63]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [64]:
b[2:3]

array([[14, 12, 12, 18]], dtype=int32)

In [65]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [66]:
b[0:-2] 

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18]], dtype=int32)

In [67]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [68]:
b[0,2] 

np.int32(10)

In [69]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [70]:
b[-5,-3] 

np.int32(17)

In [71]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [72]:
b[-4,2] 

np.int32(18)

In [73]:
np.random.randint(10,20,(4,4))

array([[15, 15, 13, 13],
       [17, 12, 17, 18],
       [12, 19, 12, 19],
       [10, 11, 17, 10]], dtype=int32)

In [74]:
b 

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [75]:
b[-4,-2]

np.int32(18)

In [76]:
b

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

In [77]:
b[-4:2] 

array([[11, 16, 18, 19]], dtype=int32)

In [78]:
b[:]

array([[16, 17, 10, 13],
       [11, 16, 18, 19],
       [14, 12, 12, 18],
       [16, 19, 14, 19],
       [19, 12, 19, 18]], dtype=int32)

## Operations

In [79]:
a = np.random.randint(10,20,10)
a

array([17, 10, 11, 13, 15, 16, 19, 14, 13, 17], dtype=int32)

In [80]:
id(a)

3034152845008

In [81]:
arr

array([0, 1, 2, 3, 4, 5])

In [82]:
arr2 = np.random.randint(0,100,(10,10))

In [83]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [84]:
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [86]:
arr

array([0, 1, 2, 3, 4, 5])

In [87]:
arr[:4] 

array([0, 1, 2, 3])

In [88]:
arr2[:]

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [89]:
arr2[0:5] 

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64]], dtype=int32)

In [90]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [91]:
arr2[1,4] 

np.int32(77)

In [92]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [93]:
arr2[-5,5] 

np.int32(77)

In [94]:
arr2[-5,-5] 

np.int32(77)

In [95]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [96]:
arr2[-5,-5]

np.int32(77)

In [97]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [98]:
arr2[-1,-2]

np.int32(3)

In [99]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [100]:
arr2[::-1]

array([[18, 20, 20, 29, 82, 41, 39, 97,  3, 13],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [81, 33, 79, 29, 15, 48,  0, 20, 25, 41]], dtype=int32)

In [101]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [102]:
arr2[::-2] 

array([[18, 20, 20, 29, 82, 41, 39, 97,  3, 13],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81]], dtype=int32)

In [103]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [104]:
arr2[::-3]

array([[18, 20, 20, 29, 82, 41, 39, 97,  3, 13],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [81, 33, 79, 29, 15, 48,  0, 20, 25, 41]], dtype=int32)

In [105]:
arr2

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64],
       [28, 59, 35, 91, 87, 63, 25,  7, 62, 34],
       [16, 68,  3, 53, 73, 74, 57, 46,  1, 52],
       [18, 20, 20, 29, 82, 41, 39, 97,  3, 13]], dtype=int32)

In [106]:
arr2[:-3] 

array([[81, 33, 79, 29, 15, 48,  0, 20, 25, 41],
       [61, 25, 42, 31, 77, 97, 37, 87, 49, 81],
       [77, 90, 82, 38, 12, 98, 97, 30, 96, 14],
       [98, 20, 86,  4, 54, 16, 68, 48, 49, 93],
       [97, 66, 46, 72, 59, 39, 39, 42,  0, 64],
       [98, 70,  2, 88, 52, 77, 79, 62, 50, 19],
       [15, 33, 67, 34, 49, 15, 20, 84,  0, 64]], dtype=int32)

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr.max() 

np.int64(5)

In [109]:
arr.min()

np.int64(0)

In [110]:
arr

array([0, 1, 2, 3, 4, 5])

In [111]:
arr.mean()

np.float64(2.5)

In [112]:
arr

array([0, 1, 2, 3, 4, 5])

In [113]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

# Without work on import* can you please find the median, mode)

In [114]:
arr

array([0, 1, 2, 3, 4, 5])

In [115]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [116]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [117]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [118]:
arr

array([0, 1, 2, 3, 4, 5])

In [119]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
arr

In [120]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [121]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [122]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
arr

array([0, 1, 2, 3, 4, 5])

In [124]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [ ]:
arr.reshape(1,6)  

In [126]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [127]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [ ]:
arr.reshape(3,3) 

In [128]:
arr

array([0, 1, 2, 3, 4, 5])

In [129]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

## Indexing

In [130]:
mat = np.arange(0,100).reshape(10,10) 

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [132]:
row = 4
col = 5

In [133]:
col

5

In [134]:
row

4

In [135]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
mat[row,col] 

np.int64(45)

In [137]:
mat[4,5] 

np.int64(45)

In [138]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
col = 6

In [141]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [142]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [143]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [145]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [147]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [148]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [149]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [150]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [151]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [152]:
row

4

In [153]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [154]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [155]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [156]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [157]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [159]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [160]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [161]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
row

4

In [163]:
col

6

In [164]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [165]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
mat[1,4]

np.int64(14)

In [167]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [168]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [169]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [174]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [178]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [179]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [180]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [193]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [197]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [199]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[0,1]

np.int64(1)

In [203]:
mat[1,6]

np.int64(16)

In [204]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [206]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [209]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [212]:
mat[3,5]

np.int64(35)

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[1:2,2:4] 

array([[12, 13]])

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[2:3,2:3] 

array([[22]])

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [219]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [220]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[2:3,4:5]

array([[24]])

## Masking

In [222]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
id(mat)

3034207873200

In [224]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [226]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [227]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [228]:
mat[mat==50] 

array([50])

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [235]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [236]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp 

In [237]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 2035


In [238]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [239]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [240]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000002C274EC69C0>


In [241]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
